trigger: 
  - master 
pool: 
  name: Default
resources:
  repositories:
    - repository: commonbuild
      type: git 
      name: commonbuild
extends:
  template: generic-maven-java.yaml@commonbuild
  parameters: 
    javadirectory: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    mavenGoal: package
    artifactPath: '**/target/gameoflife.war'
    artifactpathname: generic
    artifactdownloadpath: '/home/ubuntu/sang'




